<a href="https://colab.research.google.com/github/DR2023/pythonforAI/blob/main/Numpy_Assinment1_8_20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2D Numpy in Python


Estimated time needed: **20** minutes
    

## Objectives

After completing this you will be able to:

* Operate comfortably with `numpy`
* Perform complex operations with `numpy`


<h2>Table of Contents</h2>
<div class="alert alert-block alert-info" style="margin-top: 20px">
    <ul>
        <li><a href="create">Create a 2D Numpy Array</a></li>
        <li><a href="access">Accessing different elements of a Numpy Array</a></li>
        <li><a href="op">Basic Operations</a></li>
    </ul>
  
</div>

<hr>


<h2 id="create">Create a 2D Numpy Array</h2>


In [2]:
# Import the libraries
import numpy as np


Consider the list <code>a</code>, which contains three nested lists **each of equal size**.


In [3]:
# Create a list
a = [[1,2,3],[4,5,6],[7,8,9]]


We can cast the list to a Numpy Array as follows:


In [17]:
# Convert list to Numpy Array
# Every element is the same type
myarr = np.array(a,dtype = int)
#np.array(a,dtype = float)

We can use the attribute <code>ndim</code> to obtain the number of axes or dimensions, referred to as the rank.


In [10]:
# Show the numpy array dimensions
myarr.ndim


2

Attribute <code>shape</code> returns a tuple corresponding to the size or number of each dimension.


In [11]:
# Show the numpy array shape

myarr.shape

(3, 3)

The total number of elements in the array is given by the attribute <code>size</code>.


In [12]:
# Show the numpy array size
myarr.size


9

<hr>


<h2 id="access">Accessing different elements of a Numpy Array</h2>


We can use rectangular brackets to access the different elements of the array. The correspondence between the rectangular brackets and the list and the rectangular representation is shown in the following figure for a 3x3 array:  


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoEg.png" width="500">


We can access the 2nd-row, 3rd column as shown in the following figure:


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoFT.png" width="400">


 We simply use the square brackets and the indices corresponding to the element we would like:

Create a 3x3 matrix as above

In [16]:
# Access the element on the second row and third column

myarr[1,2]

6

We can also use slicing in numpy arrays. Consider the following figure. We would like to obtain the first two columns in the first row


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoFSF.png" width="400">


 This can be done with the following syntax:


In [14]:
# Access the element on the first row and first and second columns

myarr[[0,0],[0,1]]

array([1, 2])

Similarly, we can obtain the first two rows of the 3rd column as follows:


In [15]:
# Access the element on the first and second rows and third column

myarr[[2,0],[2,1]]

array([9, 2])

Corresponding to the following figure:


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/2D_numpy.png" width="550"><br />


<h2 id="op">Basic Operations</h2>


We can also add arrays. The process is identical to matrix addition. Matrix addition of <code>X</code> and <code>Y</code> is shown in the following figure:


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoAdd.png" width="500">


The numpy array is given by <code>X</code> and <code>Y</code>


In [26]:
# Create a numpy array X

X = np.random.random((3,3))
X

array([[0.92012268, 0.83486682, 0.05236522],
       [0.76574997, 0.69576234, 0.97222433],
       [0.87849297, 0.26000181, 0.26680119]])

In [27]:
# Create a numpy array Y

Y = np.random.random((3,3))
Y

array([[0.69200925, 0.28235899, 0.84597778],
       [0.34715323, 0.42481191, 0.96424799],
       [0.16413242, 0.77271002, 0.77004117]])

 We can add the numpy arrays as follows.


In [28]:
# Add X and Y

Z = X + Y
Z

array([[1.61213193, 1.11722582, 0.89834299],
       [1.1129032 , 1.12057425, 1.93647232],
       [1.04262539, 1.03271183, 1.03684236]])

Multiplying a numpy array by a scaler is identical to multiplying a matrix by a scaler. If we multiply the matrix <code>Y</code> by the scaler 2, we simply multiply every element in the matrix by 2, as shown in the figure.


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoDb.png" width="500">


We can perform the same operation in numpy as follows


In [30]:
# Create a numpy array Y

Y = np.random.random((3,3))
Y

array([[0.68831303, 0.98693256, 0.42079145],
       [0.46987296, 0.24073133, 0.83586763],
       [0.88425543, 0.10793518, 0.90033512]])

In [33]:
# Multiply Y with 2

Z = np.multiply(Y,2)
Z

array([[1.37662606, 1.97386511, 0.8415829 ],
       [0.93974593, 0.48146267, 1.67173525],
       [1.76851085, 0.21587036, 1.80067025]])

Multiplication of two arrays corresponds to an element-wise product or <em>Hadamard product</em>. Consider matrix <code>X</code> and <code>Y</code>. The Hadamard product corresponds to multiplying each of the elements in the same position, i.e. multiplying elements contained in the same color boxes together. The result is a new matrix that is the same size as matrix <code>Y</code> or <code>X</code>, as shown in the following figure.


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoMul.png" width="500">


We can perform element-wise product of the array <code>X</code> and <code>Y</code> as follows:


In [34]:
# Create a numpy array Y

Y = np.random.random((3,3))
Y

array([[0.23916153, 0.78271714, 0.89979247],
       [0.00224195, 0.84968283, 0.98697178],
       [0.94656645, 0.2077582 , 0.99084215]])

In [35]:
# Create a numpy array X

X = np.random.random((3,3))
X

array([[0.75721881, 0.32053274, 0.01882083],
       [0.17614073, 0.26637042, 0.10686701],
       [0.3191215 , 0.97530429, 0.40481542]])

In [37]:
# Multiply X with Y

Z = X * Y
Z

array([[1.81097609e-01, 2.50886467e-01, 1.69348370e-02],
       [3.94898920e-04, 2.26330372e-01, 1.05474723e-01],
       [3.02069705e-01, 2.02627462e-01, 4.01108179e-01]])

We can also perform matrix multiplication with the numpy arrays <code>A</code> and <code>B</code> as follows:


First, we define matrix <code>A</code> and <code>B</code>:


In [38]:
# Create a matrix A of 2x3

A = np.random.random((2,3))
A

array([[0.60623585, 0.73009617, 0.46198144],
       [0.9906956 , 0.71682561, 0.3340436 ]])

In [44]:
# Create a matrix B of 3x3

B = np.random.random((3,3))
B

array([[0.74330935, 0.22728111, 0.61236774],
       [0.41541915, 0.30796743, 0.6845855 ],
       [0.51204643, 0.36317749, 0.66177735]])

We use the numpy function <code>dot</code> to multiply the arrays together.


In [45]:
# Calculate the dot product

Z = np.dot(A,B)
Z

array([[0.99047265, 0.53041306, 1.17678138],
       [1.20522222, 0.56724246, 1.31846094]])

In [47]:
# Calculate the sine of Z
np.sin(Z)

array([[0.83628522, 0.50588969, 0.92337517],
       [0.93391868, 0.53730842, 0.968332  ]])

We use the numpy attribute <code>T</code> to calculate the transposed matrix


In [49]:
# Create a matrix C

C = np.random.random((3,3))
C

array([[0.43380555, 0.93379339, 0.98010146],
       [0.33075634, 0.35346359, 0.70058569],
       [0.85433038, 0.23855921, 0.38156816]])

In [50]:
# Get the transposed of C
C.T

array([[0.43380555, 0.33075634, 0.85433038],
       [0.93379339, 0.35346359, 0.23855921],
       [0.98010146, 0.70058569, 0.38156816]])

<h2>Quiz on 2D Numpy Array</h2>


Consider the following list <code>a</code>, convert it to Numpy Array.


In [53]:
# Create a 2D Numpy array with 3rows and 4 columns
A = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
myarr  = np.array(A)
myarr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Calculate the numpy array size.


In [54]:
# Write your code below and press Shift+Enter to execute
myarr.size

12

Access the element on the first row and first and second columns.


In [58]:
# Write your code below and press Shift+Enter to execute
myarr[0,0],myarr[0,1]

(1, 2)

Perform matrix multiplication with the numpy arrays <code>A</code> and <code>B</code>.


In [65]:
# Write your code below and press Shift+Enter to execute

B = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])
A = np.array(A)
A.T
np.dot(A,B)

array([[ 1,  4],
       [ 5, 12],
       [ 9, 20]])